export const SET_BLOCKCHAIN = "SET_BLOCKCHAIN";
export const CLEAR_BLOCKCHAIN = "CLEAR_BLOCKCHAIN";
export const BLOCKCHAIN_SET_SUCCESS = "BLOCKCHAIN_SET_SUCCESS";
export const GET_BLOCKCHAIN_START = "GET_BLOCKCHAIN_START";
export const GET_BLOCKCHAIN_SUCCESS = "GET_BLOCKCHAIN_SUCCESS";
export const GET_BLOCKCHAIN_FAIL = "GET_BLOCKCHAIN_FAIL";
export const CREATE_BLOCKCHAIN_START = "CREATE_BLOCKCHAIN_START";
export const CREATE_BLOCKCHAIN_SUCCESS = "CREATE_BLOCKCHAIN_SUCCESS";
export const CREATE_BLOCKCHAIN_FAIL = "CREATE_BLOCKCHAIN_FAIL";
export const CONSENSUS_START = "CONSENSUS_START";
export const CONSENSUS_SUCCESS = "CONSENSUS_SUCCESS";
export const CONSENSUS_FAIL = "CONSENSUS_FAIL";



const BLOCKCHAIN_ACTION_TYPES = {
  SET_BLOCKCHAIN,
  CLEAR_BLOCKCHAIN,
  BLOCKCHAIN_SET_SUCCESS,
  GET_BLOCKCHAIN_START,
  GET_BLOCKCHAIN_SUCCESS,
  GET_BLOCKCHAIN_FAIL,
  CREATE_BLOCKCHAIN_START,
  CREATE_BLOCKCHAIN_SUCCESS,
  CREATE_BLOCKCHAIN_FAIL,
  CONSENSUS_START,
  CONSENSUS_SUCCESS,
  CONSENSUS_FAIL
};

export default BLOCKCHAIN_ACTION_TYPES;
