export const SET_CURRENT_ROUTE = "SET_CURRENT_ROUTE";
export const CLEAR_CURRENT_ROUTE = "CLEAR_CURRENT_ROUTE";


const UI_ACTION_TYPES = {
  SET_CURRENT_ROUTE,
  CLEAR_CURRENT_ROUTE
};

export default UI_ACTION_TYPES;
