export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const CLEAR_TRANSACTIONS = "CLEAR_TRANSACTIONS";
export const SET_FAILED_TRANSACTIONS_UPDATES = "SET_FAILED_TRANSACTIONS_UPDATES";
export const CLEAR_FAILED_TRANSACTIONS_UPDATES = "CLEAR_FAILED_TRANSACTIONS_UPDATES";
export const TRANSACTIONS_SET_SUCCESS = "TRANSACTIONS_SET_SUCCESS";
export const CREATE_TRANSACTION_START = "CREATE_TRANSACTION_START";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_FAIL = "CREATE_TRANSACTION_FAIL";
export const GET_TRANSACTIONS_START = "GET_TRANSACTIONS_START";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAIL = "GET_TRANSACTIONS_FAIL";


const TRANSACTIONS_ACTION_TYPES = {
  SET_TRANSACTIONS,
  CLEAR_TRANSACTIONS,
  SET_FAILED_TRANSACTIONS_UPDATES,
  CLEAR_FAILED_TRANSACTIONS_UPDATES,
  TRANSACTIONS_SET_SUCCESS,
  CREATE_TRANSACTION_START,
  CREATE_TRANSACTION_SUCCESS,
  CREATE_TRANSACTION_FAIL,
  GET_TRANSACTIONS_START,
  GET_TRANSACTIONS_SUCCESS,
  GET_TRANSACTIONS_FAIL
};

export default TRANSACTIONS_ACTION_TYPES;
