export const SET_BLOCK = "SET_BLOCK";
export const CLEAR_BLOCK = "CLEAR_BLOCK";
export const BLOCK_SET_SUCCESS = "BLOCK_SET_SUCCESS";
export const GET_BLOCK_START = "GET_BLOCK_START";
export const GET_BLOCK_SUCCESS = "GET_BLOCK_SUCCESS";
export const GET_BLOCK_FAIL = "GET_BLOCK_FAIL";
export const GET_LAST_BLOCK_START = "GET_LAST_BLOCK_START";
export const GET_LAST_BLOCK_SUCCESS = "GET_LAST_BLOCK_SUCCESS";
export const GET_LAST_BLOCK_FAIL = "GET_LAST_BLOCK_FAIL";
export const CREATE_BLOCK_START = "CREATE_BLOCK_START";
export const CREATE_BLOCK_SUCCESS = "CREATE_BLOCK_SUCCESS";
export const CREATE_BLOCK_FAIL = "CREATE_BLOCK_FAIL";
export const MINE_BLOCK_START = "MINE_BLOCK_START"
export const MINE_BLOCK_SUCCESS = "MINE_BLOCK_SUCCESS"
export const MINE_BLOCK_FAIL = "MINE_BLOCK_FAIL"


const BLOCK_ACTION_TYPES = {
  SET_BLOCK,
  CLEAR_BLOCK,
  BLOCK_SET_SUCCESS,
  GET_BLOCK_START,
  GET_BLOCK_SUCCESS,
  GET_BLOCK_FAIL,
  CREATE_BLOCK_START,
  CREATE_BLOCK_SUCCESS,
  CREATE_BLOCK_FAIL,
  GET_LAST_BLOCK_START,
  GET_LAST_BLOCK_SUCCESS,
  GET_LAST_BLOCK_FAIL,
  MINE_BLOCK_START,
  MINE_BLOCK_SUCCESS,
  MINE_BLOCK_FAIL,
};

export default BLOCK_ACTION_TYPES;
