export const SET_ACCOUNT = "SET_ACCOUNT";
export const CLEAR_ACCOUNT = "CLEAR_ACCOUNT";
export const ACCOUNT_SET_SUCCESS = "ACCOUNT_SET_SUCCESS"
export const GET_ACCOUNT_DETAILS_START = "GET_ACCOUNT_DETAILS_START"
export const GET_ACCOUNT_DETAILS_SUCCESS = "GET_ACCOUNT_DETAILS_SUCCESS"
export const GET_ACCOUNT_DETAILS_FAIL = "GET_ACCOUNT_DETAILS_FAIL"
export const GET_ACCOUNT_BALANCE_START = "GET_ACCOUNT_BALANCE_START"
export const GET_ACCOUNT_BALANCE_SUCCESS = "GET_ACCOUNT_BALANCE_SUCCESS"
export const GET_ACCOUNT_BALANCE_FAIL = "GET_ACCOUNT_BALANCE_FAIL"
export const GET_ALL_ACCOUNTS_PUBLIC_KEYS_START = "GET_ALL_ACCOUNTS_PUBLIC_KEYS_START"
export const GET_ALL_ACCOUNTS_PUBLIC_KEYS_SUCCESS = "GET_ALL_ACCOUNTS_PUBLIC_KEYS_SUCCESS"
export const GET_ALL_ACCOUNTS_PUBLIC_KEYS_FAIL = "GET_ALL_ACCOUNTS_PUBLIC_KEYS_FAIL"
export const CLEAR_ALL_ACCOUNTS_PUBLIC_KEYS_FAIL = "CLEAR_ALL_ACCOUNTS_PUBLIC_KEYS_FAIL"
export const CREATE_ACCOUNT_START = "CREATE_ACCOUNT_START"
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS"
export const CREATE_ACCOUNT_FAIL = "CREATE_ACCOUNT_FAIL"

const USER_ACTION_TYPES = {
  SET_ACCOUNT,
  CLEAR_ACCOUNT,
  ACCOUNT_SET_SUCCESS,
  GET_ACCOUNT_DETAILS_START,
  GET_ACCOUNT_DETAILS_SUCCESS,
  GET_ACCOUNT_DETAILS_FAIL,
  CREATE_ACCOUNT_START,
  CREATE_ACCOUNT_SUCCESS,
  CREATE_ACCOUNT_FAIL,
  GET_ALL_ACCOUNTS_PUBLIC_KEYS_START,
  GET_ALL_ACCOUNTS_PUBLIC_KEYS_SUCCESS,
  GET_ALL_ACCOUNTS_PUBLIC_KEYS_FAIL,
  CLEAR_ALL_ACCOUNTS_PUBLIC_KEYS_FAIL,
  GET_ACCOUNT_BALANCE_START,
  GET_ACCOUNT_BALANCE_SUCCESS,
  GET_ACCOUNT_BALANCE_FAIL
};

export default USER_ACTION_TYPES;
